from .config import *

HOSTNAMES = {
    'qa2': {
        'vpntunnel': "qa2-vpntunnel.vpnsvc.com"
    }
}
HOSTNAME = HOSTNAMES[TEST_ENV][TEST_RESELLER]
SITE_URL = "https://%s:%s@%s/" % (SITE_BASIC_AUTH_USERNAME, SITE_BASIC_AUTH_PASSWORD, HOSTNAME)
WAIT_TIMEOUT = 30
DELAY_BETWEEN_ATTEMPTS = 1

CARD_NUMBER = '4242-4242-4242-4242'
CARD_EXP_MONTH = "03"
CARD_EXP_YEAR = "2019"
CARD_CVC_CODE = "111"
ZIP_POSTAL_CODE = "111111"
